codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...80"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: false
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: false

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "Tests/**/*"
  - "**/*.Tests.ps1"
  - "**/TestHelpers/**/*"
  - "**/TestData/**/*"
  - "Build/**/*"
  - "Diagnostic.ps1"
